### ISSUE TITLE
Typescript version update

### ISSUE THREAD

**Issue by cniaulin** [dbashford/mimosa-typescript#3]
Hey,

Just tried to start a mimosa project with typescript however typescript version is way too old on this module and it is almost impossible to work on a typescript project up to date. 

Do you plane an update soon ?

**Comment by dbashford** [comment]
I welcome PRs on it.  But as I'm not a TypeScript user myself, and it has always been the case that TypeScript compiling can be a bit difficult, afraid I won't have the time to patch this up.
